# Generated by Django 4.1 on 2022-08-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
