# Generated by Django 4.1 on 2022-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiloschista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Chiloschista name')),
                ('about', models.TextField(verbose_name='Chiloschista about')),
                ('img', models.ImageField(upload_to='media', verbose_name='Chiloschista image')),
            ],
        ),
    ]
